---
- name: Update Tunnel Info
  hosts: Router
  gather_facts: false
  connection: network_cli
  vars_files:
    - ./vars.yaml

  tasks:
    - name: Configuring Devices
      ios_config:
        src: "updateTunnel.j2"
